/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';
import type { IPostgresInterval } from 'postgres-interval';

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[] ? U[] : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S[], I[], U[]> : T[];

export type EstadoCancha = 'baja' | 'pendiente' | 'publicada' | 'rechazada';

export type EstadoCuenta = 'activa' | 'sin_verificar';

export type EstadoParticipacion = 'baja' | 'confirmado' | 'en_espera';

export type EstadoSolicitud = 'aprobada' | 'pendiente' | 'rechazada';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Interval = ColumnType<
  IPostgresInterval,
  IPostgresInterval | number | string,
  IPostgresInterval | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LadoEquipo = 'A' | 'B';

export type Modalidad = 'f11' | 'f5' | 'f7' | 'f8';

export type MotivoSalida = 'expulsado' | 'salio';

export type Numeric = ColumnType<string, number | string, number | string>;

export type Plataforma = 'android' | 'web';

export type QuienCalifica = 'grupos' | 'jugaron';

export type RespuestaOferta = 'aceptada' | 'rechazada' | 'vencida';

export type RolGrupo = 'admin' | 'jugador';

export type Superficie = 'cemento' | 'natural' | 'sintetico';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TipoContacto = 'llamada' | 'whatsapp';

export type TipoContenido = 'cancha' | 'nota' | 'resena';

export type TipoNotificacion =
  | 'agregado_a_grupo'
  | 'aval_rechazado'
  | 'baja_jugador'
  | 'calificacion_recibida'
  | 'cancha_aprobada'
  | 'cancha_rechazada'
  | 'confirmacion_abierta'
  | 'deuda_pendiente'
  | 'figura_abierta'
  | 'figura_elegida'
  | 'lugar_liberado'
  | 'nota_recibida'
  | 'partido_confirmado'
  | 'reclamo_aprobado'
  | 'reclamo_rechazado'
  | 'recordatorio_24h'
  | 'recordatorio_2h'
  | 'resultado_cargado'
  | 'votacion_cerrada'
  | 'votacion_nueva';

export type TipoVotacion = 'cancha' | 'horario';

export type VisibilidadPerfil = 'grupos' | 'solo_yo' | 'todos';

export interface Auditoria {
  accion: string;
  actor_usuario_id: string | null;
  creado_en: Generated<Timestamp>;
  datos: Generated<Json>;
  entidad_id: string;
  entidad_tipo: string;
  grupo_id: string | null;
  id: Generated<Int8>;
}

export interface Aval {
  avalado_en: Generated<Timestamp>;
  correcto: boolean;
  jugador_id: string;
  partido_id: string;
  version: number;
}

export interface Baja {
  baja_en: Generated<Timestamp>;
  id: Generated<string>;
  jugador_id: string;
  partido_id: string;
}

export interface Calificacion {
  actualizado_en: Generated<Timestamp>;
  calificado_usuario_id: string;
  calificador_usuario_id: string | null;
  control: number;
  fisico: number;
  id: Generated<string>;
  juego_aereo: number;
  pase: number;
  regate: number;
  resistencia: number;
  tiro: number;
  velocidad: number;
}

export interface Cancha {
  actualizado_en: Generated<Timestamp>;
  complejo_id: string | null;
  creado_en: Generated<Timestamp>;
  direccion: string;
  estado: Generated<EstadoCancha>;
  id: Generated<string>;
  modalidades: Generated<ArrayType<Modalidad>>;
  nombre: string;
  oculto_en: Timestamp | null;
  precio_hora: number | null;
  propuesta_por: string | null;
  revisada_en: Timestamp | null;
  revisada_por: string | null;
  superficies: Generated<ArrayType<Superficie>>;
  techada: Generated<boolean>;
  telefono: string | null;
  ubicacion: string | null;
  whatsapp: string | null;
  zona: string | null;
}

export interface CanchaFoto {
  cancha_id: string;
  creado_en: Generated<Timestamp>;
  id: Generated<string>;
  orden: Generated<number>;
  storage_key: string;
  subida_por: string | null;
}

export interface Complejo {
  creado_en: Generated<Timestamp>;
  encargado_usuario_id: string | null;
  id: Generated<string>;
  nombre: string;
  verificado_en: Timestamp | null;
}

export interface ContactoCancha {
  cancha_id: string;
  creado_en: Generated<Timestamp>;
  id: Generated<Int8>;
  tipo: TipoContacto;
  usuario_id: string | null;
}

export interface Credencial {
  actualizado_en: Timestamp;
  alcance: string | null;
  contrasena_hash: string | null;
  creado_en: Generated<Timestamp>;
  cuenta_id: string;
  id: Generated<string>;
  proveedor_id: string;
  token_acceso: string | null;
  token_acceso_expira_en: Timestamp | null;
  token_id: string | null;
  token_refresco: string | null;
  token_refresco_expira_en: Timestamp | null;
  usuario_id: string;
}

export interface Denuncia {
  contenido_id: string;
  creado_en: Generated<Timestamp>;
  denunciante_id: string;
  id: Generated<string>;
  motivo: string | null;
  resolucion: string | null;
  resuelta_en: Timestamp | null;
  resuelta_por: string | null;
  tipo: TipoContenido;
}

export interface Dispositivo {
  creado_en: Generated<Timestamp>;
  id: Generated<string>;
  plataforma: Plataforma;
  push_token: string;
  sesion_id: string | null;
  ultimo_uso_en: Generated<Timestamp>;
  usuario_id: string;
}

export interface Grupo {
  borrado_en: Timestamp | null;
  creado_en: Generated<Timestamp>;
  creador_usuario_id: string | null;
  id: Generated<string>;
  link_regenerado_en: Timestamp | null;
  link_token: string;
  nombre: string;
}

export interface IntentoInicio {
  actualizado_en: Generated<Timestamp>;
  bloqueado_hasta: Timestamp | null;
  email_hash: Buffer;
  fallidos_consecutivos: number;
}

export interface InvitadoToken {
  creado_en: Generated<Timestamp>;
  expira_en: Timestamp;
  id: Generated<string>;
  jugador_id: string;
  proposito: string;
  token_hash: Buffer;
  usado_en: Timestamp | null;
}

export interface Jugador {
  creado_en: Generated<Timestamp>;
  eliminado_en: Timestamp | null;
  email: string | null;
  email_verificado_en: Timestamp | null;
  fusionado_a: string | null;
  grupo_invitado_id: string | null;
  id: Generated<string>;
  nombre: string | null;
  usuario_id: string | null;
}

export interface MetricaDiaria {
  clave: string;
  fecha: Timestamp;
  valor: Int8;
}

export interface Miembro {
  grupo_id: string;
  jugador_id: string;
  motivo_salida: MotivoSalida | null;
  rol: Generated<RolGrupo>;
  salida_en: Timestamp | null;
  silenciado: Generated<boolean>;
  unido_en: Generated<Timestamp>;
}

export interface Nota {
  autor_usuario_id: string;
  creado_en: Generated<Timestamp>;
  destinatario_usuario_id: string;
  id: Generated<string>;
  oculto_en: Timestamp | null;
  texto: string;
}

export interface Notificacion {
  creada_en: Generated<Timestamp>;
  datos: Generated<Json>;
  grupo_id: string | null;
  id: Generated<string>;
  leida_en: Timestamp | null;
  partido_id: string | null;
  tipo: TipoNotificacion;
  usuario_id: string;
}

export interface NotificacionDesactivada {
  tipo: TipoNotificacion;
  usuario_id: string;
}

export interface Opcion {
  cancha_id: string | null;
  cancha_texto: string | null;
  id: Generated<string>;
  inicio: Timestamp | null;
  orden: Generated<number>;
  tipo: TipoVotacion;
  votacion_id: string;
}

export interface Outbox {
  agregado_id: string;
  agregado_tipo: string;
  creado_en: Generated<Timestamp>;
  evento: string;
  id: Generated<Int8>;
  intentos: Generated<number>;
  payload: Generated<Json>;
  procesado_en: Timestamp | null;
  ultimo_error: string | null;
}

export interface Participacion {
  asistencias: Generated<number>;
  confirmado_en: Generated<Timestamp>;
  equipo_id: string | null;
  estado: EstadoParticipacion;
  goles: Generated<number>;
  id: Generated<string>;
  jugador_id: string;
  oferta_enviada_en: Timestamp | null;
  oferta_respuesta: RespuestaOferta | null;
  oferta_vence_en: Timestamp | null;
  pagado_en: Timestamp | null;
  pago_marcado_por: string | null;
  partido_id: string;
}

export interface Partido {
  cancelado_en: Timestamp | null;
  cancelado_por: string | null;
  cancha_id: string | null;
  cancha_texto: string | null;
  confirmacion_abre_en: Timestamp;
  costo_total: number | null;
  creado_en: Generated<Timestamp>;
  creado_por: string | null;
  fecha_serie: Timestamp | null;
  grupo_id: string;
  id: Generated<string>;
  inicio: Timestamp;
  modalidad: Modalidad;
  motivo_cancelacion: string | null;
  resultado_cargado_en: Timestamp | null;
  resultado_version: Generated<number>;
  serie_id: string | null;
  votacion_cancha_id: string | null;
  votacion_horario_id: string | null;
}

export interface PartidoEquipo {
  goles: number | null;
  grupo_id: string | null;
  id: Generated<string>;
  lado: LadoEquipo;
  nombre: string;
  partido_id: string;
}

export interface ReclamoComplejo {
  cancha_id: string;
  creado_en: Generated<Timestamp>;
  estado: Generated<EstadoSolicitud>;
  evidencia: string | null;
  id: Generated<string>;
  revisado_en: Timestamp | null;
  revisado_por: string | null;
  usuario_id: string;
}

export interface ReporteCancha {
  cancha_id: string;
  creado_en: Generated<Timestamp>;
  id: Generated<string>;
  motivo: string;
  resuelto_en: Timestamp | null;
  resuelto_por: string | null;
  usuario_id: string | null;
}

export interface Resena {
  autor_usuario_id: string;
  cancha_id: string;
  creado_en: Generated<Timestamp>;
  editado_en: Timestamp | null;
  id: Generated<string>;
  oculto_en: Timestamp | null;
  puntaje: number;
  texto: string | null;
}

export interface Serie {
  cancha_id: string | null;
  cancha_texto: string | null;
  creada_por: string | null;
  creado_en: Generated<Timestamp>;
  desde: Timestamp;
  dia_semana: number;
  grupo_id: string;
  hasta: Timestamp | null;
  hora: string;
  id: Generated<string>;
  modalidad: Modalidad;
  reemplaza_a: string | null;
  zona_horaria: Generated<string>;
}

export interface Sesion {
  actualizado_en: Timestamp;
  agente: string | null;
  creado_en: Generated<Timestamp>;
  expira_en: Timestamp;
  id: Generated<string>;
  ip: string | null;
  token: string;
  usuario_id: string;
}

export interface SolicitudHistorial {
  creado_en: Generated<Timestamp>;
  estado: Generated<EstadoSolicitud>;
  id: Generated<string>;
  invitado_jugador_id: string;
  revisado_en: Timestamp | null;
  revisado_por: string | null;
  usuario_id: string;
}

export interface Usuario {
  actualizado_en: Generated<Timestamp>;
  creado_en: Generated<Timestamp>;
  email: string;
  email_verificado: Generated<boolean>;
  email_verificado_en: Timestamp | null;
  estado: Generated<EstadoCuenta>;
  fecha_nacimiento: Timestamp;
  id: Generated<string>;
  imagen: string | null;
  nombre_usuario: string;
  privacidad_aceptada_en: Timestamp;
  quien_califica: Generated<QuienCalifica>;
  recibe_calificaciones: Generated<boolean>;
  visibilidad_perfil: Generated<VisibilidadPerfil>;
}

export interface VAvales {
  avales: Int8 | null;
  partido_id: string | null;
  rechazos: Int8 | null;
}

export interface VBaja {
  antelacion: Interval | null;
  baja_en: Timestamp | null;
  grupo_id: string | null;
  id: string | null;
  inicio: Timestamp | null;
  jugador_id: string | null;
  partido_id: string | null;
}

export interface VCanchaPublica {
  complejo_registrado: boolean | null;
  direccion: string | null;
  id: string | null;
  modalidades: ArrayType<Modalidad> | null;
  nombre: string | null;
  precio_hora: number | null;
  puntaje: Numeric | null;
  resenas: Int8 | null;
  superficies: ArrayType<Superficie> | null;
  techada: boolean | null;
  telefono: string | null;
  ubicacion: string | null;
  whatsapp: string | null;
  zona: string | null;
}

export interface VDeuda {
  deuda: number | null;
  grupo_id: string | null;
  jugador_id: string | null;
}

export interface Verificacion {
  actualizado_en: Generated<Timestamp>;
  creado_en: Generated<Timestamp>;
  expira_en: Timestamp;
  id: Generated<string>;
  identificador: string;
  valor: string;
}

export interface VEstadisticasGlobal {
  asistencias: number | null;
  figuras: Int8 | null;
  goles: number | null;
  pe: Int8 | null;
  pg: Int8 | null;
  pj: Int8 | null;
  pp: Int8 | null;
  usuario_id: string | null;
}

export interface VEstadisticasGrupo {
  asistencias: number | null;
  figuras: Int8 | null;
  goles: number | null;
  grupo_id: string | null;
  jugador_id: string | null;
  pe: Int8 | null;
  pg: Int8 | null;
  pj: Int8 | null;
  pp: Int8 | null;
}

export interface VFigura {
  cerrada: boolean | null;
  jugador_id: string | null;
  partido_id: string | null;
  votos: Int8 | null;
}

export interface VGrupoActivo {
  grupo_id: string | null;
  partidos_30d: Int8 | null;
}

export interface VJugador {
  eliminado: boolean | null;
  es_invitado: boolean | null;
  fusionado_a: string | null;
  jugador_id: string | null;
  nombre_visible: string | null;
  usuario_id: string | null;
}

export interface VListaEspera {
  confirmado_en: Timestamp | null;
  jugador_id: string | null;
  oferta_respuesta: RespuestaOferta | null;
  oferta_vence_en: Timestamp | null;
  partido_id: string | null;
  posicion: Int8 | null;
}

export interface Votacion {
  cerrada_en: Timestamp | null;
  cierra_en: Timestamp | null;
  creada_por: string | null;
  creado_en: Generated<Timestamp>;
  grupo_id: string;
  id: Generated<string>;
  opcion_ganadora_id: string | null;
  tipo: TipoVotacion;
}

export interface Voto {
  jugador_id: string;
  opcion_id: string;
  votado_en: Generated<Timestamp>;
}

export interface VotoFigura {
  partido_id: string;
  votado_en: Generated<Timestamp>;
  votado_id: string;
  votante_id: string;
}

export interface VParte {
  grupo_id: string | null;
  jugador_id: string | null;
  pagado_en: Timestamp | null;
  parte: number | null;
  partido_id: string | null;
}

export interface VParticipante {
  asistencias: number | null;
  cancha_id: string | null;
  goles: number | null;
  goles_contra: number | null;
  goles_favor: number | null;
  grupo_id: string | null;
  inicio: Timestamp | null;
  jugador_id: string | null;
  partido_id: string | null;
  resultado: string | null;
}

export interface VPartido {
  cancelado_en: Timestamp | null;
  cancelado_por: string | null;
  cancha_id: string | null;
  cancha_texto: string | null;
  confirmacion_abre_en: Timestamp | null;
  confirmados: Int8 | null;
  costo_total: number | null;
  creado_en: Timestamp | null;
  creado_por: string | null;
  cupo: number | null;
  en_espera: Int8 | null;
  estado: string | null;
  fecha_serie: Timestamp | null;
  grupo_id: string | null;
  id: string | null;
  inicio: Timestamp | null;
  modalidad: Modalidad | null;
  motivo_cancelacion: string | null;
  resultado_cargado_en: Timestamp | null;
  resultado_version: number | null;
  serie_id: string | null;
  votacion_cancha_id: string | null;
  votacion_horario_id: string | null;
}

export interface VRadar {
  calificaciones: Int8 | null;
  control: Numeric | null;
  fisico: Numeric | null;
  juego_aereo: Numeric | null;
  pase: Numeric | null;
  regate: Numeric | null;
  resistencia: Numeric | null;
  tiro: Numeric | null;
  usuario_id: string | null;
  velocidad: Numeric | null;
}

export interface VVotacionResultado {
  abierta: boolean | null;
  hay_empate: boolean | null;
  opcion_id: string | null;
  primera: boolean | null;
  votacion_id: string | null;
  votos: Int8 | null;
}

export interface DB {
  auditoria: Auditoria;
  aval: Aval;
  baja: Baja;
  calificacion: Calificacion;
  cancha: Cancha;
  cancha_foto: CanchaFoto;
  complejo: Complejo;
  contacto_cancha: ContactoCancha;
  credencial: Credencial;
  denuncia: Denuncia;
  dispositivo: Dispositivo;
  grupo: Grupo;
  intento_inicio: IntentoInicio;
  invitado_token: InvitadoToken;
  jugador: Jugador;
  metrica_diaria: MetricaDiaria;
  miembro: Miembro;
  nota: Nota;
  notificacion: Notificacion;
  notificacion_desactivada: NotificacionDesactivada;
  opcion: Opcion;
  outbox: Outbox;
  participacion: Participacion;
  partido: Partido;
  partido_equipo: PartidoEquipo;
  reclamo_complejo: ReclamoComplejo;
  reporte_cancha: ReporteCancha;
  resena: Resena;
  serie: Serie;
  sesion: Sesion;
  solicitud_historial: SolicitudHistorial;
  usuario: Usuario;
  v_avales: VAvales;
  v_baja: VBaja;
  v_cancha_publica: VCanchaPublica;
  v_deuda: VDeuda;
  v_estadisticas_global: VEstadisticasGlobal;
  v_estadisticas_grupo: VEstadisticasGrupo;
  v_figura: VFigura;
  v_grupo_activo: VGrupoActivo;
  v_jugador: VJugador;
  v_lista_espera: VListaEspera;
  v_parte: VParte;
  v_participante: VParticipante;
  v_partido: VPartido;
  v_radar: VRadar;
  v_votacion_resultado: VVotacionResultado;
  verificacion: Verificacion;
  votacion: Votacion;
  voto: Voto;
  voto_figura: VotoFigura;
}
