/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado de la API
         * @description Responde si la API está en línea y puede consultar la base. Hito M0 de docs/ROADMAP.md; no implementa un requisito del SRS.
         */
        get: operations["consultarSalud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cuentas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear una cuenta
         * @description RF-001, RF-002, RF-003, RN-20 y RNF-018. Crea la cuenta en estado "Sin verificar" y manda el mail de verificación (RF-004). No inicia sesión.
         */
        post: operations["registrarCuenta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cuentas/sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión en la web
         * @description RF-005 y RNF-011. Deja la sesión en una cookie HttpOnly, Secure y SameSite=Lax (ADR 0009). Para Android se usa iniciarSesionConToken.
         */
        post: operations["iniciarSesion"];
        /**
         * Cerrar la sesión del dispositivo actual
         * @description RF-007. Borra la sesión (y el dispositivo registrado con ella, que deja de recibir push) y vence la cookie de la web.
         */
        delete: operations["cerrarSesion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cuentas/sesion/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión en Android
         * @description RF-005, RNF-011 y RNF-012. Devuelve un bearer que dura 30 días desde el último uso (ADR 0009). No deja cookie.
         */
        post: operations["iniciarSesionConToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cuentas/yo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * La cuenta de la sesión actual
         * @description RF-004, RF-005 y RNF-012. Dice si hay sesión y si la cuenta está verificada. Usarla corre el vencimiento de la sesión (en la web, con una cookie nueva).
         */
        get: operations["consultarCuentaActual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cuentas/verificacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verificar el mail con el enlace
         * @description RF-004 y RNF-014. Activa la cuenta. El enlace vence a las 24 horas y sirve una sola vez: si la cuenta ya está activa, se rechaza.
         */
        post: operations["verificarEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cuentas/verificacion/reenvio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reenviar el mail de verificación
         * @description RF-004. Responde igual exista o no la cuenta, para no revelar cuáles existen.
         */
        post: operations["reenviarVerificacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cuentas/recuperacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pedir el mail para definir una contraseña nueva
         * @description RF-006. Responde igual exista o no la cuenta. El enlace vence en 1 hora.
         */
        post: operations["pedirRecuperacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cuentas/recuperacion/confirmacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Definir la contraseña nueva con el enlace
         * @description RF-006 y RNF-014. El enlace sirve una sola vez. Cierra todas las sesiones abiertas de la cuenta.
         */
        post: operations["restablecerContrasena"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/grupos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mis grupos
         * @description RF-010 y RF-011. Los grupos donde quien tiene la sesión es miembro, ordenados por nombre.
         */
        get: operations["listarMisGrupos"];
        put?: never;
        /**
         * Crear un grupo
         * @description RF-010. Quien lo crea queda como admin y se genera el link de invitación. Requiere la cuenta verificada (RF-004).
         */
        post: operations["crearGrupo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/grupos/{grupoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Un grupo
         * @description RNF-013, RN-07 y RN-26. Solo para miembros; a los demás se les responde como si no existiera. El link viene solo para admins y `acciones` dice qué puede hacer el rol.
         */
        get: operations["consultarGrupo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/grupos/{grupoId}/link/regeneracion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerar el link de invitación
         * @description RF-012. Solo un admin. El link anterior deja de funcionar y el nuevo queda vigente sin vencimiento. Devuelve el grupo con el link nuevo.
         */
        post: operations["regenerarLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invitaciones/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ver un link de invitación antes de aceptarlo
         * @description RF-011 y RN-27. Solo con sesión: nombre del grupo, cantidad de miembros y qué pasa si acepta.
         */
        get: operations["consultarInvitacion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invitaciones/{token}/aceptacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unirse a un grupo con el link
         * @description RF-011, RF-004 y RN-28. Sin aprobación de un admin. Si ya es miembro, no duplica la membresía. Quien había salido vuelve como jugador; el expulsado no.
         */
        post: operations["unirsePorLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SolicitudDeAltaInput: {
            /**
             * Format: email
             * @description Mail de la cuenta
             */
            email: string;
            /** @description Entre 8 y 128 caracteres */
            contrasena: string;
            /** @description 3 a 20 letras minúsculas, números, punto o guion bajo (RF-003). Se guarda en minúsculas. */
            nombreUsuario: string;
            /**
             * Format: date
             * @description AAAA-MM-DD (RF-002)
             */
            fechaNacimiento: string;
            /** @description Aceptación de la política de privacidad (RNF-018) */
            aceptaPrivacidad: boolean;
        };
        SolicitudDeInicioInput: {
            /**
             * Format: email
             * @description Mail de la cuenta
             */
            email: string;
            contrasena: string;
        };
        SolicitudConEmailInput: {
            /**
             * Format: email
             * @description Mail de la cuenta
             */
            email: string;
        };
        SolicitudDeVerificacionInput: {
            /** @description Token del enlace del mail */
            token: string;
        };
        SolicitudDeRestablecimientoInput: {
            /** @description Token del enlace del mail */
            token: string;
            contrasenaNueva: string;
        };
        SolicitudDeGrupoInput: {
            /** @description De 1 a 60 caracteres sin contar los espacios de los extremos (RF-010) */
            nombre: string;
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description ID del requisito del SRS, si aplica */
            requisito?: string;
            /** @description Detalle por campo cuando la solicitud no es válida */
            errores?: {
                campo: string;
                mensaje: string;
            }[];
        };
        /** @enum {string} */
        EstadoDeCuenta: "sin_verificar" | "activa";
        Cuenta: {
            /** Format: uuid */
            id: string;
            email: string;
            nombreUsuario: string;
            estado: components["schemas"]["EstadoDeCuenta"];
        };
        CuentaCreada: {
            email: string;
            nombreUsuario: string;
            /** @constant */
            estado: "sin_verificar";
        };
        SesionConToken: {
            /** @description Bearer para `Authorization`. Vence a los 30 días sin uso (RNF-012). */
            token: string;
            cuenta: components["schemas"]["Cuenta"];
        };
        /** @enum {string} */
        RolEnGrupo: "jugador" | "admin";
        /**
         * @description Acción que el rol permite en el grupo (RN-07, RN-26). Los clientes muestran solo estas.
         * @enum {string}
         */
        AccionDeGrupo: "ver_link" | "regenerar_link" | "crear_votacion" | "crear_partido" | "armar_equipos" | "cargar_resultado" | "registrar_costo" | "marcar_pago";
        Grupo: {
            /** Format: uuid */
            id: string;
            nombre: string;
            cantidadMiembros: number;
            rol: components["schemas"]["RolEnGrupo"];
            /** @description Link de invitación vigente (RF-011). Solo lo ven los admins (RN-26); si no, null. */
            link: string | null;
            acciones: components["schemas"]["AccionDeGrupo"][];
        };
        ResumenDeGrupo: {
            /** Format: uuid */
            id: string;
            nombre: string;
            cantidadMiembros: number;
            rol: components["schemas"]["RolEnGrupo"];
        };
        ListaDeGrupos: {
            grupos: components["schemas"]["ResumenDeGrupo"][];
        };
        /**
         * @description Qué pasa si acepta: se une; ya es miembro y va al grupo (RF-011); tiene que verificar el mail (RF-004); o fue expulsado y no puede volver por link (RN-28).
         * @enum {string}
         */
        EstadoDeInvitacion: "puede_unirse" | "ya_es_miembro" | "cuenta_sin_verificar" | "expulsado";
        Invitacion: {
            /** Format: uuid */
            grupoId: string;
            nombre: string;
            cantidadMiembros: number;
            estado: components["schemas"]["EstadoDeInvitacion"];
        };
        Union: {
            /** Format: uuid */
            grupoId: string;
            /** @description true si ya era miembro: no se duplicó la membresía */
            yaEraMiembro: boolean;
        };
        Salud: {
            /** @constant */
            estado: "ok";
            /** @description Versión desplegada de la API */
            version: string;
            /**
             * Format: date-time
             * @description Hora del servidor
             */
            instante: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    consultarSalud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La API y la base responden */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Salud"];
                };
            };
            /** @description La base no responde */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    registrarCuenta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudDeAltaInput"];
            };
        };
        responses: {
            /** @description Cuenta creada sin verificar */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CuentaCreada"];
                };
            };
            /** @description El mail (RF-001) o el nombre de usuario (RF-003) ya están en uso */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Menor de 18 años (RF-002), nombre de usuario o fecha inválidos, o sin aceptar la privacidad (RNF-018) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    iniciarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudDeInicioInput"];
            };
        };
        responses: {
            /** @description Sesión iniciada; la cookie viaja en Set-Cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cuenta"];
                };
            };
            /** @description El mail o la contraseña no son correctos, sin decir cuál (RF-005) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Inicio de sesión bloqueado por intentos fallidos (RNF-011). El encabezado Retry-After dice en cuántos segundos termina. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    cerrarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión cerrada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No hay sesión */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    iniciarSesionConToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudDeInicioInput"];
            };
        };
        responses: {
            /** @description Sesión iniciada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionConToken"];
                };
            };
            /** @description El mail o la contraseña no son correctos, sin decir cuál (RF-005) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Inicio de sesión bloqueado por intentos fallidos (RNF-011). El encabezado Retry-After dice en cuántos segundos termina. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    consultarCuentaActual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cuenta de la sesión */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cuenta"];
                };
            };
            /** @description No hay sesión */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    verificarEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudDeVerificacionInput"];
            };
        };
        responses: {
            /** @description Cuenta activa */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El enlace venció o no es válido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description El enlace ya se usó (RNF-014) */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    reenviarVerificacion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudConEmailInput"];
            };
        };
        responses: {
            /** @description Si la cuenta existe y no está verificada, se manda el mail */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pedirRecuperacion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudConEmailInput"];
            };
        };
        responses: {
            /** @description Si la cuenta existe, se manda el mail */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restablecerContrasena: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudDeRestablecimientoInput"];
            };
        };
        responses: {
            /** @description Contraseña cambiada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El enlace venció, no es válido o ya se usó */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listarMisGrupos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grupos del usuario */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaDeGrupos"];
                };
            };
            /** @description No hay sesión */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    crearGrupo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudDeGrupoInput"];
            };
        };
        responses: {
            /** @description Grupo creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grupo"];
                };
            };
            /** @description No hay sesión */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description La cuenta no está verificada (RF-004) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description El nombre no tiene entre 1 y 60 caracteres */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    consultarGrupo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grupoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grupo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grupo"];
                };
            };
            /** @description No hay sesión */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description El grupo no existe o no es miembro */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    regenerarLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grupoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grupo con el link nuevo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grupo"];
                };
            };
            /** @description No hay sesión */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No es admin del grupo (RF-012, RN-07) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description El grupo no existe o no es miembro */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    consultarInvitacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Token del link de invitación */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitación vigente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitacion"];
                };
            };
            /** @description No hay sesión */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description El link no existe o se regeneró (RF-011) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    unirsePorLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Token del link de invitación */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Es miembro del grupo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Union"];
                };
            };
            /** @description No hay sesión */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Cuenta sin verificar (RF-004) o expulsado del grupo (RN-28) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description El link no existe o se regeneró (RF-011) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
