/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado de la API
         * @description Responde si la API está en línea y puede consultar la base. Hito M0 de docs/ROADMAP.md; no implementa un requisito del SRS.
         */
        get: operations["consultarSalud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description ID del requisito del SRS, si aplica */
            requisito?: string;
            /** @description Detalle por campo cuando la solicitud no es válida */
            errores?: {
                campo: string;
                mensaje: string;
            }[];
        };
        Salud: {
            /** @constant */
            estado: "ok";
            /** @description Versión desplegada de la API */
            version: string;
            /**
             * Format: date-time
             * @description Hora del servidor
             */
            instante: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    consultarSalud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La API y la base responden */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Salud"];
                };
            };
            /** @description La base no responde */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
